### ISSUE TITLE
API throws an error when using pinecone 

### ISSUE THREAD

**Issue by navacmo** [sametcodes/product-taxonomy#7]
I have setup the project locally and using both the OpenAI and pinecone api keys. I have also created an index in pinecone account. This is what it shows when I call the api in postman

{{host}}/category/predict/shopify

input: iphone pro max
deepSearch: true

Error: 
![product_taxonomy_issue](https://github.com/sametcodes/product-taxonomy/assets/138220278/2464841e-8e82-4a8e-825b-f780bd900c3e)

**Comment by sametcodes** [comment]
We considered to remove pinecore support (https://github.com/sametcodes/product-taxonomy/issues/9), and probably implement it later with advanced options.
